Added regex parsing for webpage legacy thread dumps.
paul-griffith/kindling pull request #80
Opened 2022-11-03 16:06 UTC by CorbinH

Also fixed script thread dump regex to include the entire stack (before it only grabbed the first character of the stack)

2022-11-03 17:33 UTC, paul-griffith requested changes
Need to figure out why the test is failing, but code overall looks good beside some nitpicks.

2022-11-03 17:33 UTC, paul-griffith commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +                    deadlocksPattern.findAll(lines[3]).map { match -> match.value.toInt() }.toList()
Is that final `toList` actually doing anything? I didn't notice it in the first review, but I suspect it's not necessary.

2022-11-03 17:33 UTC, paul-griffith commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +        private val webThreadStackRegex = """^(?<line>(?!waiting |owns ).*)$""".toRegex(RegexOption.MULTILINE)
These don't need to be raw strings (triple quoted), do they?

2022-11-03 17:33 UTC, paul-griffith commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +        """.trimIndent().toRegex()
I think I prefer the actual pattern indented in one more tab stop, so it's clearly part of the same string (see line 58:63 above)

2022-11-03 17:33 UTC, paul-griffith commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +                }.toList()
Again, unnecessary final `toList` (there's a couple more down below as well)

2022-11-03 22:25 UTC, CorbinH commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +                    deadlocksPattern.findAll(lines[3]).map { match -> match.value.toInt() }.toList()
It looks like the map function for MatchGroups actually returns a Sequence object instead of a List.

2022-11-03 22:53 UTC, paul-griffith commented on thread/src/main/kotlin/io/github/paulgriffith/kindling/thread/model/ThreadDump.kt
> +                    deadlocksPattern.findAll(lines[3]).map { match -> match.value.toInt() }.toList()
So it does - carry on

2022-11-04 00:05 UTC, paul-griffith approved these changes

2022-11-04 00:06 UTC, merged